# Generated by Django 3.2.18 on 2023-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_academic_beijing_beijinghangkonghangtian_beijingligong_beijingshifan_chongqing_dalianligong_dianzike'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorAcademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('school_is', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'major_academic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MajorProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('school_is', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'major_professional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('subordinate', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate', models.CharField(blank=True, max_length=255, null=True)),
                ('zhx', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school_list',
                'managed': False,
            },
        ),
    ]
