# Generated by Django 3.2.18 on 2023-04-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_majoracademic_majorprofessional_schoollist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhxSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zhx_school',
                'managed': False,
            },
        ),
    ]
