# Generated by Django 3.2.18 on 2023-04-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_zhxschool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beijing',
        ),
        migrations.DeleteModel(
            name='Beijinghangkonghangtian',
        ),
        migrations.DeleteModel(
            name='Beijingligong',
        ),
        migrations.DeleteModel(
            name='Beijingshifan',
        ),
        migrations.DeleteModel(
            name='Chongqing',
        ),
        migrations.DeleteModel(
            name='Dalianligong',
        ),
        migrations.DeleteModel(
            name='Dianzikeji',
        ),
        migrations.DeleteModel(
            name='Dongbei',
        ),
        migrations.DeleteModel(
            name='Dongnan',
        ),
        migrations.DeleteModel(
            name='Fudan',
        ),
        migrations.DeleteModel(
            name='Haerbingongye',
        ),
        migrations.DeleteModel(
            name='Huananligong',
        ),
        migrations.DeleteModel(
            name='Huazhongkeji',
        ),
        migrations.DeleteModel(
            name='Hunan',
        ),
        migrations.DeleteModel(
            name='Jilin',
        ),
        migrations.DeleteModel(
            name='Lanzhou',
        ),
        migrations.DeleteModel(
            name='Nanjing',
        ),
        migrations.DeleteModel(
            name='Nankai',
        ),
        migrations.DeleteModel(
            name='Qinghua',
        ),
        migrations.DeleteModel(
            name='Shandong',
        ),
        migrations.DeleteModel(
            name='Shanghaijiaotong',
        ),
        migrations.DeleteModel(
            name='Sichuan',
        ),
        migrations.DeleteModel(
            name='Tianjin',
        ),
        migrations.DeleteModel(
            name='Tongji',
        ),
        migrations.DeleteModel(
            name='Xiamen',
        ),
        migrations.DeleteModel(
            name='Xianjiaotong',
        ),
        migrations.DeleteModel(
            name='Xibeigongye',
        ),
        migrations.DeleteModel(
            name='Zhejiang',
        ),
        migrations.DeleteModel(
            name='Zhongguokexuejishu',
        ),
        migrations.DeleteModel(
            name='Zhongguonongye',
        ),
        migrations.DeleteModel(
            name='Zhongguorenmin',
        ),
        migrations.DeleteModel(
            name='Zhongnan',
        ),
        migrations.DeleteModel(
            name='Zhongshan',
        ),
    ]
