# Generated by Django 3.2.18 on 2023-04-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20230420_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiquSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('regular_total', models.IntegerField(blank=True, null=True)),
                ('regular_central', models.IntegerField(blank=True, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('higher', models.IntegerField(blank=True, null=True)),
                ('adult_total', models.IntegerField(blank=True, null=True)),
                ('adult_central', models.IntegerField(blank=True, null=True)),
                ('government', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diqu_school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiquStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('graduates_total', models.IntegerField(blank=True, null=True)),
                ('graduates_female', models.IntegerField(blank=True, null=True)),
                ('graduates_doctor', models.IntegerField(blank=True, null=True)),
                ('graduates_master', models.IntegerField(blank=True, null=True)),
                ('degree_awarded', models.IntegerField(blank=True, null=True)),
                ('entrants_total', models.IntegerField(blank=True, null=True)),
                ('entrants_female', models.IntegerField(blank=True, null=True)),
                ('entrants_doctor', models.IntegerField(blank=True, null=True)),
                ('entrants_master', models.IntegerField(blank=True, null=True)),
                ('enrolment_total', models.IntegerField(blank=True, null=True)),
                ('enrolment_female', models.IntegerField(blank=True, null=True)),
                ('enrolment_doctor', models.IntegerField(blank=True, null=True)),
                ('enrolment_master', models.IntegerField(blank=True, null=True)),
                ('nextyear_total', models.IntegerField(blank=True, db_column='nextYear_total', null=True)),
                ('nextyear_female', models.IntegerField(blank=True, db_column='nextYear_female', null=True)),
                ('nextyear_doctor', models.IntegerField(blank=True, db_column='nextYear_doctor', null=True)),
                ('nextyear_master', models.IntegerField(blank=True, db_column='nextYear_master', null=True)),
            ],
            options={
                'db_table': 'diqu_student',
                'managed': False,
            },
        ),
    ]
