# Generated by Django 3.2.18 on 2023-04-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_diquschool_diqustudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School2014',
        ),
        migrations.DeleteModel(
            name='School2015',
        ),
        migrations.DeleteModel(
            name='School2016',
        ),
        migrations.DeleteModel(
            name='School2017',
        ),
        migrations.DeleteModel(
            name='School2018',
        ),
        migrations.DeleteModel(
            name='School2019',
        ),
        migrations.DeleteModel(
            name='School2020',
        ),
        migrations.DeleteModel(
            name='Student2014',
        ),
        migrations.DeleteModel(
            name='Student2015',
        ),
        migrations.DeleteModel(
            name='Student2016',
        ),
        migrations.DeleteModel(
            name='Student2017',
        ),
        migrations.DeleteModel(
            name='Student2018',
        ),
        migrations.DeleteModel(
            name='Student2019',
        ),
        migrations.DeleteModel(
            name='Student2020',
        ),
    ]
